export const environment = {
  production: true,
  isAdmin: false,
  baseUrl: 'https://mycode.rtuitlab.dev',
  buildNumber: 'test build number',
  showResults: true,
  redirectUrl: 'http://localhost:4201',
  token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIzNzA2MzEwNC1iNGNmLTRlYzYtODhiMi1kODI0ZmFmNzVkOWIiLCJpYXQiOjE2MDQxNTM0MjcsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbkBsb2NhbGhvc3QucnUiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiQWRtaW4iLCJVc2VyIiwiRXhlY3V0b3IiLCJSZXN1bHRzVmlld2VyIl0sImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNWIwYTRhNGEtZDc0Ny00OGM3LTg3NDUtOWQwYjgzYWU4NWYxIiwibmJmIjoxNjA0MTUzNDI3LCJleHAiOjE2MTQ1MjE0Mjd9.M9KRQUeiNxq4bW0thdl9hWPVTILrLEMftNwMLQf02Jk'
};
